language: node_js
node_js:
  - 10
  - 12
  - node

install: yarn
cache: yarn

script:
  - yarn lint
  - yarn test

deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_KEY"
    on:
        tags: true
